const seats = [
    { airplaneId: 33, row: 1, col: 'A', TravelClass: 'First-class', status: 'Available', isWindowSeat: true, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 33, row: 1, col: 'B', TravelClass: 'First-class', status: 'Booked', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 33, row: 1, col: 'C', TravelClass: 'First-class', status: 'Available', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 33, row: 1, col: 'D', TravelClass: 'First-class', status: 'Reserved', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 33, row: 1, col: 'E', TravelClass: 'First-class', status: 'Available', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 33, row: 1, col: 'F', TravelClass: 'First-class', status: 'Blocked', isWindowSeat: true, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 33, row: 2, col: 'A', TravelClass: 'First-class', status: 'Available', isWindowSeat: true, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 33, row: 2, col: 'B', TravelClass: 'First-class', status: 'Available', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 33, row: 2, col: 'C', TravelClass: 'First-class', status: 'Booked', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 33, row: 2, col: 'D', TravelClass: 'First-class', status: 'Available', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 33, row: 2, col: 'E', TravelClass: 'First-class', status: 'Reserved', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 33, row: 2, col: 'F', TravelClass: 'First-class', status: 'Available', isWindowSeat: true, createdAt: new Date(), updatedAt: new Date() },
  
    { airplaneId: 33, row: 4, col: 'A', TravelClass: 'Business', status: 'Booked', isWindowSeat: true, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 33, row: 4, col: 'B', TravelClass: 'Business', status: 'Available', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 33, row: 4, col: 'C', TravelClass: 'Business', status: 'Available', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 33, row: 4, col: 'D', TravelClass: 'Business', status: 'Available', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 33, row: 4, col: 'E', TravelClass: 'Business', status: 'Blocked', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 33, row: 4, col: 'F', TravelClass: 'Business', status: 'Reserved', isWindowSeat: true, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 33, row: 5, col: 'A', TravelClass: 'Business', status: 'Available', isWindowSeat: true, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 33, row: 5, col: 'B', TravelClass: 'Business', status: 'Available', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 33, row: 5, col: 'C', TravelClass: 'Business', status: 'Available', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 33, row: 5, col: 'D', TravelClass: 'Business', status: 'Booked', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 33, row: 5, col: 'E', TravelClass: 'Business', status: 'Available', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 33, row: 5, col: 'F', TravelClass: 'Business', status: 'Blocked', isWindowSeat: true, createdAt: new Date(), updatedAt: new Date() },
  
    { airplaneId: 33, row: 7, col: 'A', TravelClass: 'Economy', status: 'Available', isWindowSeat: true, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 33, row: 7, col: 'B', TravelClass: 'Economy', status: 'Booked', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 33, row: 7, col: 'C', TravelClass: 'Economy', status: 'Available', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 33, row: 7, col: 'D', TravelClass: 'Economy', status: 'Reserved', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 33, row: 7, col: 'E', TravelClass: 'Economy', status: 'Available', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 33, row: 7, col: 'F', TravelClass: 'Economy', status: 'Blocked', isWindowSeat: true, createdAt: new Date(), updatedAt: new Date() },
  
    { airplaneId: 33, row: 8, col: 'A', TravelClass: 'Economy', status: 'Available', isWindowSeat: true, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 33, row: 8, col: 'B', TravelClass: 'Economy', status: 'Booked', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 33, row: 8, col: 'C', TravelClass: 'Economy', status: 'Available', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 33, row: 8, col: 'D', TravelClass: 'Economy', status: 'Reserved', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 33, row: 8, col: 'E', TravelClass: 'Economy', status: 'Available', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 33, row: 8, col: 'F', TravelClass: 'Economy', status: 'Blocked', isWindowSeat: true, createdAt: new Date(), updatedAt: new Date() },
  
    { airplaneId: 33, row: 9, col: 'A', TravelClass: 'Economy', status: 'Available', isWindowSeat: true, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 33, row: 9, col: 'B', TravelClass: 'Economy', status: 'Available', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 1, col: 'A', TravelClass: 'First-class', status: 'Available', isWindowSeat: true, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 1, col: 'B', TravelClass: 'First-class', status: 'Booked', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 1, col: 'C', TravelClass: 'First-class', status: 'Available', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 1, col: 'D', TravelClass: 'First-class', status: 'Reserved', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 1, col: 'E', TravelClass: 'First-class', status: 'Available', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 1, col: 'F', TravelClass: 'First-class', status: 'Blocked', isWindowSeat: true, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 2, col: 'A', TravelClass: 'First-class', status: 'Available', isWindowSeat: true, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 2, col: 'B', TravelClass: 'First-class', status: 'Available', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 2, col: 'C', TravelClass: 'First-class', status: 'Booked', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 2, col: 'D', TravelClass: 'First-class', status: 'Available', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 2, col: 'E', TravelClass: 'First-class', status: 'Reserved', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 2, col: 'F', TravelClass: 'First-class', status: 'Available', isWindowSeat: true, createdAt: new Date(), updatedAt: new Date() },

    { airplaneId: 45, row: 4, col: 'A', TravelClass: 'Business', status: 'Booked', isWindowSeat: true, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 4, col: 'B', TravelClass: 'Business', status: 'Available', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 4, col: 'C', TravelClass: 'Business', status: 'Available', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 4, col: 'D', TravelClass: 'Business', status: 'Available', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 4, col: 'E', TravelClass: 'Business', status: 'Blocked', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 4, col: 'F', TravelClass: 'Business', status: 'Reserved', isWindowSeat: true, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 5, col: 'A', TravelClass: 'Business', status: 'Available', isWindowSeat: true, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 5, col: 'B', TravelClass: 'Business', status: 'Available', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 5, col: 'C', TravelClass: 'Business', status: 'Available', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 5, col: 'D', TravelClass: 'Business', status: 'Booked', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 5, col: 'E', TravelClass: 'Business', status: 'Available', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 5, col: 'F', TravelClass: 'Business', status: 'Blocked', isWindowSeat: true, createdAt: new Date(), updatedAt: new Date() },

    { airplaneId: 45, row: 7, col: 'A', TravelClass: 'Economy', status: 'Available', isWindowSeat: true, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 7, col: 'B', TravelClass: 'Economy', status: 'Booked', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 7, col: 'C', TravelClass: 'Economy', status: 'Available', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 7, col: 'D', TravelClass: 'Economy', status: 'Reserved', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 7, col: 'E', TravelClass: 'Economy', status: 'Available', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 7, col: 'F', TravelClass: 'Economy', status: 'Blocked', isWindowSeat: true, createdAt: new Date(), updatedAt: new Date() },

    { airplaneId: 45, row: 8, col: 'A', TravelClass: 'Economy', status: 'Available', isWindowSeat: true, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 8, col: 'B', TravelClass: 'Economy', status: 'Booked', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 8, col: 'C', TravelClass: 'Economy', status: 'Available', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 8, col: 'D', TravelClass: 'Economy', status: 'Reserved', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 8, col: 'E', TravelClass: 'Economy', status: 'Available', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 8, col: 'F', TravelClass: 'Economy', status: 'Blocked', isWindowSeat: true, createdAt: new Date(), updatedAt: new Date() },

    { airplaneId: 45, row: 9, col: 'A', TravelClass: 'Economy', status: 'Available', isWindowSeat: true, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 9, col: 'B', TravelClass: 'Economy', status: 'Available', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 9, col: 'C', TravelClass: 'Economy', status: 'Booked', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 9, col: 'D', TravelClass: 'Economy', status: 'Reserved', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 9, col: 'E', TravelClass: 'Economy', status: 'Available', isWindowSeat: false, createdAt: new Date(), updatedAt: new Date() },
    { airplaneId: 45, row: 9, col: 'F', TravelClass: 'Economy', status: 'Blocked', isWindowSeat: true, createdAt: new Date(), updatedAt: new Date() }
  ];

  module.exports = seats